name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building deb package
        run: |
          sudo apt update
          sudo apt install devscripts equivs -yq
          yes | sudo mk-build-deps -i
          DEB_BUILD_OPTIONS=noautodbgsym sudo dpkg-buildpackage -b
          sudo mkdir -p /output/
          sudo mv ../*.deb /output/
          sudo mv ./*.deb /output/
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "bozuk-paket"
          prerelease: false
          title: "bozuk paket"
          files: |
            /output/*

